In [1]:
import pandas as pd
import numpy as np
import pybaseball as pb
from pybaseball import cache
from datetime import date, timedelta, datetime
import time
cache.enable()

In [2]:
team_data = pb.team_batting(start_season=2024)
team_data.to_csv("data/team_batting.csv")
team_data.iloc[:,1:50].columns

Index(['Season', 'Team', 'Age', 'G', 'AB', 'PA', 'H', '1B', '2B', '3B', 'HR',
       'R', 'RBI', 'BB', 'IBB', 'SO', 'HBP', 'SF', 'SH', 'GDP', 'SB', 'CS',
       'AVG', 'GB', 'FB', 'LD', 'IFFB', 'Pitches', 'Balls', 'Strikes', 'IFH',
       'BU', 'BUH', 'BB%', 'K%', 'BB/K', 'OBP', 'SLG', 'OPS', 'ISO', 'BABIP',
       'GB/FB', 'LD%', 'GB%', 'FB%', 'IFFB%', 'HR/FB', 'IFH%', 'BUH%'],
      dtype='object')

In [3]:
team_data.iloc[:,50:100].columns

Index(['wOBA', 'wRAA', 'wRC', 'Bat', 'Fld', 'Rep', 'Pos', 'RAR', 'WAR', 'Dol',
       'Spd', 'wRC+', 'WPA', '-WPA', '+WPA', 'RE24', 'REW', 'pLI', 'phLI',
       'PH', 'WPA/LI', 'Clutch', 'FB% (Pitch)', 'FBv', 'SL%', 'SLv', 'CT%',
       'CTv', 'CB%', 'CBv', 'CH%', 'CHv', 'SF%', 'SFv', 'KN%', 'KNv', 'XX%',
       'PO%', 'wFB', 'wSL', 'wCT', 'wCB', 'wCH', 'wSF', 'wKN', 'wFB/C',
       'wSL/C', 'wCT/C', 'wCB/C', 'wCH/C'],
      dtype='object')

In [4]:
team_data.iloc[:,100:150].columns

Index(['wSF/C', 'wKN/C', 'O-Swing%', 'Z-Swing%', 'Swing%', 'O-Contact%',
       'Z-Contact%', 'Contact%', 'Zone%', 'F-Strike%', 'SwStr%', 'BsR',
       'FA% (sc)', 'FT% (sc)', 'FC% (sc)', 'FS% (sc)', 'FO% (sc)', 'SI% (sc)',
       'SL% (sc)', 'CU% (sc)', 'KC% (sc)', 'EP% (sc)', 'CH% (sc)', 'SC% (sc)',
       'KN% (sc)', 'UN% (sc)', 'vFA (sc)', 'vFT (sc)', 'vFC (sc)', 'vFS (sc)',
       'vFO (sc)', 'vSI (sc)', 'vSL (sc)', 'vCU (sc)', 'vKC (sc)', 'vEP (sc)',
       'vCH (sc)', 'vSC (sc)', 'vKN (sc)', 'FA-X (sc)', 'FT-X (sc)',
       'FC-X (sc)', 'FS-X (sc)', 'FO-X (sc)', 'SI-X (sc)', 'SL-X (sc)',
       'CU-X (sc)', 'KC-X (sc)', 'EP-X (sc)', 'CH-X (sc)'],
      dtype='object')

In [5]:
team_data.iloc[:,150:200].columns

Index(['SC-X (sc)', 'KN-X (sc)', 'FA-Z (sc)', 'FT-Z (sc)', 'FC-Z (sc)',
       'FS-Z (sc)', 'FO-Z (sc)', 'SI-Z (sc)', 'SL-Z (sc)', 'CU-Z (sc)',
       'KC-Z (sc)', 'EP-Z (sc)', 'CH-Z (sc)', 'SC-Z (sc)', 'KN-Z (sc)',
       'wFA (sc)', 'wFT (sc)', 'wFC (sc)', 'wFS (sc)', 'wFO (sc)', 'wSI (sc)',
       'wSL (sc)', 'wCU (sc)', 'wKC (sc)', 'wEP (sc)', 'wCH (sc)', 'wSC (sc)',
       'wKN (sc)', 'wFA/C (sc)', 'wFT/C (sc)', 'wFC/C (sc)', 'wFS/C (sc)',
       'wFO/C (sc)', 'wSI/C (sc)', 'wSL/C (sc)', 'wCU/C (sc)', 'wKC/C (sc)',
       'wEP/C (sc)', 'wCH/C (sc)', 'wSC/C (sc)', 'wKN/C (sc)', 'O-Swing% (sc)',
       'Z-Swing% (sc)', 'Swing% (sc)', 'O-Contact% (sc)', 'Z-Contact% (sc)',
       'Contact% (sc)', 'Zone% (sc)', 'Pace', 'Def'],
      dtype='object')

In [6]:
team_data.iloc[:,200:250].columns

Index(['wSB', 'UBR', 'Age Rng', 'Off', 'Lg', 'wGDP', 'Pull%', 'Cent%', 'Oppo%',
       'Soft%', 'Med%', 'Hard%', 'TTO%', 'CH% (pi)', 'CS% (pi)', 'CU% (pi)',
       'FA% (pi)', 'FC% (pi)', 'FS% (pi)', 'KN% (pi)', 'SB% (pi)', 'SI% (pi)',
       'SL% (pi)', 'XX% (pi)', 'vCH (pi)', 'vCS (pi)', 'vCU (pi)', 'vFA (pi)',
       'vFC (pi)', 'vFS (pi)', 'vKN (pi)', 'vSB (pi)', 'vSI (pi)', 'vSL (pi)',
       'vXX (pi)', 'CH-X (pi)', 'CS-X (pi)', 'CU-X (pi)', 'FA-X (pi)',
       'FC-X (pi)', 'FS-X (pi)', 'KN-X (pi)', 'SB-X (pi)', 'SI-X (pi)',
       'SL-X (pi)', 'XX-X (pi)', 'CH-Z (pi)', 'CS-Z (pi)', 'CU-Z (pi)',
       'FA-Z (pi)'],
      dtype='object')

In [7]:
team_data.iloc[:,250:300].columns

Index(['FC-Z (pi)', 'FS-Z (pi)', 'KN-Z (pi)', 'SB-Z (pi)', 'SI-Z (pi)',
       'SL-Z (pi)', 'XX-Z (pi)', 'wCH (pi)', 'wCS (pi)', 'wCU (pi)',
       'wFA (pi)', 'wFC (pi)', 'wFS (pi)', 'wKN (pi)', 'wSB (pi)', 'wSI (pi)',
       'wSL (pi)', 'wXX (pi)', 'wCH/C (pi)', 'wCS/C (pi)', 'wCU/C (pi)',
       'wFA/C (pi)', 'wFC/C (pi)', 'wFS/C (pi)', 'wKN/C (pi)', 'wSB/C (pi)',
       'wSI/C (pi)', 'wSL/C (pi)', 'wXX/C (pi)', 'O-Swing% (pi)',
       'Z-Swing% (pi)', 'Swing% (pi)', 'O-Contact% (pi)', 'Z-Contact% (pi)',
       'Contact% (pi)', 'Zone% (pi)', 'Pace (pi)', 'FRM', 'AVG+', 'BB%+',
       'K%+', 'OBP+', 'SLG+', 'ISO+', 'BABIP+', 'LD+%', 'GB%+', 'FB%+',
       'HR/FB%+', 'Pull%+'],
      dtype='object')

In [8]:
team_data.iloc[:,300:].columns

Index(['Cent%+', 'Oppo%+', 'Soft%+', 'Med%+', 'Hard%+', 'EV', 'LA', 'Barrels',
       'Barrel%', 'maxEV', 'HardHit', 'HardHit%', 'Events', 'CStr%', 'CSW%',
       'xBA', 'xSLG', 'xwOBA', 'L-WAR'],
      dtype='object')

In [9]:
team_data = team_data[['Team', 'Age', 'G', 'AB', 'PA', 'H', '1B', '2B', '3B', 'HR',
       'R', 'RBI', 'BB', 'IBB', 'SO', 'HBP', 'SF', 'SH', 'GDP', 'SB', 'CS',
       'AVG', 'GB', 'FB', 'LD', 'IFFB', 'Pitches', 'Balls', 'Strikes', 'IFH',
       'BU', 'BUH', 'BB%', 'K%', 'BB/K', 'OBP', 'SLG', 'OPS', 'ISO', 'BABIP',
       'GB/FB', 'LD%', 'GB%', 'FB%', 'IFFB%', 'HR/FB', 'IFH%', 'BUH%','wOBA', 'wRAA', 'wRC', 'Bat', 'Fld', 'Rep', 'Pos', 'RAR', 'WAR', 'Dol',
       'Spd', 'wRC+', 'WPA', '-WPA', '+WPA', 'RE24', 'REW', 'pLI', 'phLI',
       'PH', 'WPA/LI', 'Clutch', 'FB% (Pitch)', 'FBv', 'SL%', 'SLv', 'CT%',
       'CTv', 'CB%', 'CBv', 'CH%', 'CHv', 'SF%', 'SFv', 'KN%', 'KNv', 'XX%',
       'PO%', 'wFB', 'wSL', 'wCT', 'wCB', 'wCH', 'wSF', 'wKN', 'wFB/C',
       'wSL/C', 'wCT/C', 'wCB/C', 'wCH/C','O-Swing%', 'Z-Swing%', 'Swing%', 'O-Contact%',
       'Z-Contact%', 'Contact%', 'Zone%', 'F-Strike%', 'SwStr%', 'BsR','O-Swing% (sc)',
       'Z-Swing% (sc)', 'Swing% (sc)', 'O-Contact% (sc)', 'Z-Contact% (sc)',
       'Contact% (sc)', 'Zone% (sc)', 'Pace', 'Def','FRM', 'AVG+', 'BB%+',
       'K%+', 'OBP+', 'SLG+', 'ISO+', 'BABIP+', 'LD+%', 'GB%+', 'FB%+',
       'HR/FB%+', 'Pull%+','Cent%+', 'Oppo%+', 'Soft%+', 'Med%+', 'Hard%+', 'EV', 'LA', 'Barrels',
       'Barrel%', 'maxEV', 'HardHit', 'HardHit%', 'Events', 'CStr%', 'CSW%',
       'xBA', 'xSLG', 'xwOBA']]
team_data.dropna(axis = 1)
team_data.head()

,Team,Age,G,AB,PA,H,1B,2B,3B,HR,...,Barrel%,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA
0,NYY,29,1946,4617,5285,1161,725,211,15,210,...,0.107,120.0,1507,0.421,3583,0.177,0.272,NaN,NaN,NaN
1,ARI,28,2045,4663,5293,1223,787,231,33,172,...,0.079,117.0,1440,0.389,3700,0.172,0.264,NaN,NaN,NaN
2,LAD,30,2006,4663,5274,1182,721,253,21,187,...,0.091,119.2,1459,0.409,3571,0.159,0.266,NaN,NaN,NaN
3,BAL,28,2036,4737,5250,1187,723,228,30,206,...,0.093,114.4,1552,0.426,3647,0.159,0.266,NaN,NaN,NaN
4,BOS,29,2027,4757,5273,1220,749,271,28,172,...,0.088,114.7,1424,0.410,3476,0.163,0.283,NaN,NaN,NaN

In [10]:
sdate = date(2024,8,27)
edate = datetime.today()-timedelta(days=1)
edate = datetime.strftime(edate, '%Y-%m-%d')
dates = pd.date_range(sdate,edate,freq='d')
dates = list(dates.format())
# remove = ['2024-07-15', '2024-07-16', '2024-07-17', '2024-07-18']
# print(dates)
# for x in remove:
#     dates.remove(x)
# print(dates)
dfs = []
for x in dates:
    print(x)
    time.sleep(15)
    pdd = pb.pitching_stats_range(x)
    dfs.append(pdd)
# pitch_data_daily = pb.pitching_stats_range("2023-05-28")
pitch_data_daily = pd.concat(dfs)
pdd = pd.read_csv("data/aug_27_pitch_daily.csv", index_col = 0)
pddfs = [pdd, pitch_data_daily]
pitch_data_daily = pd.concat(pddfs)
pitch_data_daily.to_csv("data/pitcher_daily_stats.csv")
pitch_data_daily.head()

2024-08-27
2024-08-28
2024-08-29
2024-08-30
2024-08-31
2024-09-01

,Name,Age,#days,Lev,Date,Tm,,Opp,G,GS,...,StL,StS,GB/FB,LD,PU,WHIP,BAbip,SO9,SO/W,mlbID
1,Albert Abreu,27,100,Maj-AL,"Apr 30, 2023",New York,@,Texas,1,0,...,0.15,0.05,0.50,0.25,0.0,6.0,0.333,9.0,0.25,656061
2,Bryan Abreu,26,100,Maj-AL,"Apr 30, 2023",Houston,NaN,Philadelphia,1,0,...,0.14,0.09,1.00,0.00,0.0,1.0,0.000,9.0,1.00,650556
3,Domingo Acevedo,29,100,Maj-AL,"Apr 30, 2023",Oakland,NaN,Cincinnati,1,0,...,0.11,0.00,0.33,0.67,0.0,9.0,0.667,0.0,0.00,642758
4,Jason Adam,31,100,Maj-AL,"Apr 30, 2023",Tampa Bay,@,Chicago,1,0,...,0.19,0.10,0.67,0.33,0.0,1.0,0.333,18.0,NaN,592094
5,Scott Alexander,33,100,Maj-NL,"Apr 30, 2023",San Francisco,@,San Diego,1,0,...,0.22,0.11,1.00,0.00,0.0,0.0,0.000,9.0,NaN,518397

In [11]:
pitch_data_daily.to_csv('data/sep_2_pitch_daily.csv')

In [12]:
daily_ks = pitch_data_daily[['Name', 'SO', 'Opp', 'GS', 'Date']]
daily_ks_S = daily_ks[daily_ks["GS"] == 1]
daily_ks_S = daily_ks_S.rename(columns = {"SO":"K"})
daily_ks_S = daily_ks_S.drop(columns = "GS")
daily_ks_S.head()

              Name  K        Opp          Date
6      Logan Allen  8     Boston  Apr 30, 2023
11   Chris Bassitt  7    Seattle  Apr 30, 2023
16    Kyle Bradish  5    Detroit  Apr 30, 2023
23  Mike Clevinger  8  Tampa Bay  Apr 30, 2023
24       Alex Cobb  7  San Diego  Apr 30, 2023

In [13]:
pitch_season = pb.pitching_stats(2024, qual = 0)
pitch_season.shape

(799, 393)

In [14]:
pitch_season = pitch_season[['Name', 'Team','W', 'L', 'WAR', 'ERA','CG', 'ShO','IP', 'TBF', 'H', 'R', 'ER', 'HR', 'BB',
       'IBB', 'HBP', 'WP', 'BK', 'SO', 'GB', 'FB', 'LD', 'IFFB', 'Balls',
       'Strikes', 'Pitches', 'RS', 'IFH', 'BU', 'BUH', 'K/9', 'BB/9', 'K/BB',
       'H/9', 'HR/9', 'AVG', 'WHIP', 'BABIP', 'LOB%', 'FIP', 'GB/FB', 'LD%','GB%', 
       'FB%', 'IFFB%', 'HR/FB', 'IFH%', 'BUH%', 'tERA', 'xFIP', 'WPA',
       '-WPA', '+WPA', 'RE24', 'REW', 'pLI', 'inLI', 'gmLI', 'exLI', 'Pulls',
       'WPA/LI', 'Clutch', 'FB% 2', 'FBv', 'SL%', 'SLv', 'CT%', 'CTv', 'CB%',
       'CBv', 'CH%', 'CHv', 'SF%', 'SFv', 'KN%', 'KNv', 'XX%', 'PO%', 'wFB',
       'wSL', 'wCT', 'wCB', 'wCH', 'wSF', 'wKN', 'wFB/C','wSL/C', 'wCT/C', 'wCB/C', 'wCH/C', 'wSF/C', 'wKN/C', 'O-Swing%',
       'Z-Swing%', 'Swing%', 'O-Contact%', 'Z-Contact%', 'Contact%', 'Zone%',
       'F-Strike%', 'SwStr%', 'HLD', 'SD', 'MD', 'ERA-', 'FIP-', 'xFIP-', 'K%',
       'BB%', 'SIERA', 'RS/9', 'E-F','K-BB%', 'Pull%',
       'Cent%', 'Oppo%', 'Soft%', 'Med%', 'Hard%', 'kwERA', 'TTO%','Pace (pi)', 'FRM', 'K/9+', 'BB/9+', 'K/BB+', 'H/9+', 'HR/9+', 'AVG+',
       'WHIP+', 'BABIP+', 'LOB%+', 'K%+', 'BB%+', 'LD%+', 'GB%+', 'FB%+',
       'HR/FB%+', 'Pull%+', 'Cent%+', 'Oppo%+', 'Soft%+', 'Med%+', 'Hard%+',
       'EV', 'LA', 'Barrels', 'Barrel%', 'maxEV', 'HardHit', 'HardHit%',
       'Events', 'CStr%', 'CSW%', 'xERA']]
pitch_season.to_csv("data/pitcher_season_stats.csv")
pitch_season.head()
print(len(pitch_season.columns))

156

In [15]:
pitch_all = pitch_season.merge(daily_ks_S, on = "Name")
pitch_all.to_csv("data/pitcher_season_daily.csv")
pitch_all.head()

,Name,Team,W,L,WAR,ERA,CG,ShO,IP,TBF,...,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xERA,K,Opp,Date
0,Chris Sale,ATL,14,3,5.4,2.62,0,0,147.2,584,...,114.4,105,0.297,354,0.191,0.332,2.68,5,Cleveland,"Apr 30, 2023"
1,Chris Sale,ATL,14,3,5.4,2.62,0,0,147.2,584,...,114.4,105,0.297,354,0.191,0.332,2.68,10,Philadelphia,"May 5, 2023"
2,Chris Sale,ATL,14,3,5.4,2.62,0,0,147.2,584,...,114.4,105,0.297,354,0.191,0.332,2.68,9,St. Louis,"May 13, 2023"
3,Chris Sale,ATL,14,3,5.4,2.62,0,0,147.2,584,...,114.4,105,0.297,354,0.191,0.332,2.68,8,San Diego,"May 20, 2023"
4,Chris Sale,ATL,14,3,5.4,2.62,0,0,147.2,584,...,114.4,105,0.297,354,0.191,0.332,2.68,3,Arizona,"May 26, 2023"

In [16]:
teams1 = team_data['Team'].unique().tolist()
teams1

['NYY',
 'ARI',
 'LAD',
 'BAL',
 'BOS',
 'SDP',
 'PHI',
 'MIL',
 'MIN',
 'NYM',
 'HOU',
 'KCR',
 'ATL',
 'CHC',
 'TOR',
 'STL',
 'CLE',
 'CIN',
 'OAK',
 'COL',
 'SFG',
 'WSN',
 'TEX',
 'DET',
 'TBR',
 'LAA',
 'PIT',
 'SEA',
 'MIA',
 'CHW']

In [17]:
team_data = team_data.replace(teams1, ['Atlanta', 'Tampa Bay', 'Texas', 'Los Angeles', 'Los Angeles', 'Boston', 
                                       'Arizona', 'San Francisco', 'Toronto', 'St. Louis', 'Baltimore', 'Philadelphia', 
                                       'Cincinnati', 'Chicago', 'New York', 'Pittsburgh', 'Miami', 'San Diego', 'Colorado', 
                                       'Washington', 'Houston', 'Minnesota', 'New York', 'Seattle', 'Milwaukee', 'Cleveland', 
                                       'Chicago', 'Kansas City', 'Detroit', 'Oakland'])
team_data.columns

Index(['Team', 'Age', 'G', 'AB', 'PA', 'H', '1B', '2B', '3B', 'HR',
       ...
       'Barrel%', 'maxEV', 'HardHit', 'HardHit%', 'Events', 'CStr%', 'CSW%',
       'xBA', 'xSLG', 'xwOBA'],
      dtype='object', length=148)

In [18]:
team_data['Team'].unique()
team_data.to_csv('data/team_batting.csv')
print(len(team_data.columns))

148

In [19]:
full_df = pitch_all.merge(team_data, left_on = "Opp", right_on = "Team")
full_df.head(30)
full_df = full_df.drop(columns = ['Team_y', 'Dol', 'Name'])
print(full_df.select_dtypes(include = 'object').columns)
full_df[['Team_x', 'Opp', 'K', 'Date']].head()

Index(['Team_x', 'Opp', 'Date'], dtype='object')

  Team_x        Opp  K          Date
0    ATL  Cleveland  5  Apr 30, 2023
1    ATL  Cleveland  6  Apr 26, 2024
2    ATL  Cleveland  6  Apr 26, 2024
3    ATL  Cleveland  6  Apr 26, 2024
4    ATL  Cleveland  6  Apr 26, 2024

In [20]:
full_df.to_csv("data/all_stats.csv")