# Data Collection for Pitcher Strikeout Prediction

This notebook explores the data collection process using the `mlb_data` package.

Data sources:
- **Pitcher game logs**: Daily pitching stats from Statcast (100% accurate team IDs)
- **Team batting stats**: Season batting statistics for opponent analysis
- **Pitcher season stats**: Season-level pitching statistics

In [5]:
import sys
sys.path.insert(0, '..')

from datetime import datetime, timedelta

import pandas as pd

# Import from mlb_data package
from mlb_data import (
    get_pitcher_game_logs,
    get_pitcher_season_stats,
    get_team_batting,
    get_statcast_pitches,
    ALL_TEAMS,
    list_teams,
)

# Import config
from src.config import (
    SEASONS,
    DATA_START,
    DATA_END,
    DATA_DIR,
)

pd.set_option('display.max_columns', 50)

print(f"Seasons: {SEASONS}")
print(f"Date range: {DATA_START} to {DATA_END}")

Seasons: [2021, 2022, 2023, 2024]
Date range: 2021-04-01 to 2026-04-08

In [ ]:
# Memory management utilities
import gc
import psutil

def clear_mem():
    """Run garbage collection and print memory usage."""
    gc.collect()
    mem_gb = psutil.Process().memory_info().rss / 1024**3
    print(f"Memory: {mem_gb:.2f} GB")
    return mem_gb

clear_mem()

## Team Abbreviations

All 30 MLB teams with unambiguous abbreviations:

In [6]:
list_teams()

MLB Team Abbreviations:
--------------------------------------------------
  ARI: Arizona Diamondbacks (NL)
  ATL: Atlanta Braves (NL)
  BAL: Baltimore Orioles (AL)
  BOS: Boston Red Sox (AL)
  CHC: Chicago Cubs (NL)
  CHW: Chicago White Sox (AL)
  CIN: Cincinnati Reds (NL)
  CLE: Cleveland Guardians (AL)
  COL: Colorado Rockies (NL)
  DET: Detroit Tigers (AL)
  HOU: Houston Astros (AL)
  KCR: Kansas City Royals (AL)
  LAA: Los Angeles Angels (AL)
  LAD: Los Angeles Dodgers (NL)
  MIA: Miami Marlins (NL)
  MIL: Milwaukee Brewers (NL)
  MIN: Minnesota Twins (AL)
  NYM: New York Mets (NL)
  NYY: New York Yankees (AL)
  OAK: Oakland Athletics (AL)
  PHI: Philadelphia Phillies (NL)
  PIT: Pittsburgh Pirates (NL)
  SDP: San Diego Padres (NL)
  SEA: Seattle Mariners (AL)
  SFG: San Francisco Giants (NL)
  STL: St. Louis Cardinals (NL)
  TBR: Tampa Bay Rays (AL)
  TEX: Texas Rangers (AL)
  TOR: Toronto Blue Jays (AL)
  WSN: Washington Nationals (NL)

## Team Batting Stats

Season-level batting statistics for each team. Used to assess opponent difficulty.

In [ ]:
# # Collect team batting stats for all seasons
# team_batting_list = []
# for season in SEASONS:
#     print(f"Fetching team batting for {season}...")
#     df = get_team_batting(season)
#     df['season'] = season
#     team_batting_list.append(df)

# team_batting = pd.concat(team_batting_list, ignore_index=True)
# print(f"\nTotal shape: {team_batting.shape}")
# team_batting.head(10)

Fetching team batting for 2021...
Fetching team batting stats for 2021...

HTTPError: Error accessing 'https://www.fangraphs.com/leaders-legacy.aspx'. Received status code 403

In [ ]:
# Available columns
# print("Team batting columns:")
# print(team_batting.columns.tolist())

Team batting columns:

NameError: name 'team_batting' is not defined

## Pitcher Game Logs

Daily pitching statistics from Statcast. This is the primary data source with accurate team identification.

Key columns:
- `pitcher_id`: Unique MLB player ID
- `Name`: Pitcher name
- `team_abbrev`: Pitcher's team (e.g., NYY, LAD)
- `opp_abbrev`: Opponent team (e.g., BOS, CHC)
- `SO`: Strikeouts (our target variable)
- `IP`: Innings pitched
- `pitches`: Total pitches thrown

In [ ]:
# Collect pitcher game logs for full date range
# Note: This uses Statcast and may take several minutes for large date ranges

pitcher_games = get_pitcher_game_logs(
    start_date=DATA_START,
    end_date=DATA_END,
    starters_only=True,  # Only starting pitchers
)

print(f"Shape: {pitcher_games.shape}")
print(f"Date range: {pitcher_games['game_date'].min()} to {pitcher_games['game_date'].max()}")
pitcher_games.head(10)

Fetching pitcher game logs from 2021-04-01 to 2026-03-31...
  Fetching 2021-04-01 to 2021-04-30...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:51<00:00,  1.70s/it]

  Fetching 2021-05-01 to 2021-05-30...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:47<00:00,  1.58s/it]

  Fetching 2021-05-31 to 2021-06-29...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:48<00:00,  1.60s/it]

  Fetching 2021-06-30 to 2021-07-29...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:47<00:00,  1.59s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Fetching 2021-07-30 to 2021-08-28...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:49<00:00,  1.65s/it]

  Fetching 2021-08-29 to 2021-09-27...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:47<00:00,  1.57s/it]

  Fetching 2021-09-28 to 2021-10-27...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:49<00:00,  1.67s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Fetching 2021-10-28 to 2021-11-26...
This is a large query, it may take a moment to complete
Skipping offseason dates

100%|██████████| 19/19 [00:31<00:00,  1.67s/it]

  Fetching 2021-11-27 to 2021-12-26...
This is a large query, it may take a moment to complete

/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

Skipping offseason dates

0it [00:00, ?it/s]

  Fetching 2021-12-27 to 2022-01-25...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  Fetching 2022-01-26 to 2022-02-24...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  Fetching 2022-02-25 to 2022-03-26...
This is a large query, it may take a moment to complete

Skipping offseason dates

100%|██████████| 12/12 [00:20<00:00,  1.68s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Fetching 2022-03-27 to 2022-04-25...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:47<00:00,  1.60s/it]

  Fetching 2022-04-26 to 2022-05-25...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:48<00:00,  1.60s/it]

  Fetching 2022-05-26 to 2022-06-24...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:54<00:00,  1.82s/it]

  Fetching 2022-06-25 to 2022-07-24...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:56<00:00,  1.87s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Fetching 2022-07-25 to 2022-08-23...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:52<00:00,  1.76s/it]

  Fetching 2022-08-24 to 2022-09-22...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [03:24<00:00,  6.81s/it]

  Fetching 2022-09-23 to 2022-10-22...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:50<00:00,  1.68s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Fetching 2022-10-23 to 2022-11-21...
This is a large query, it may take a moment to complete
Skipping offseason dates

100%|██████████| 24/24 [00:40<00:00,  1.67s/it]

  Fetching 2022-11-22 to 2022-12-21...
This is a large query, it may take a moment to complete

/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

Skipping offseason dates

0it [00:00, ?it/s]

  Fetching 2022-12-22 to 2023-01-20...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  Fetching 2023-01-21 to 2023-02-19...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  Fetching 2023-02-20 to 2023-03-21...
This is a large query, it may take a moment to complete

Skipping offseason dates

 14%|█▍        | 1/7 [00:12<01:12, 12.16s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 71%|███████▏  | 5/7 [00:13<00:04,  2.01s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 7/7 [00:13<00:00,  1.94s/it]

  Fetching 2023-03-22 to 2023-04-20...
This is a large query, it may take a moment to complete

  3%|▎         | 1/30 [00:19<09:37, 19.92s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  7%|▋         | 2/30 [00:20<04:05,  8.76s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 10%|█         | 3/30 [00:21<02:15,  5.00s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 13%|█▎        | 4/30 [00:21<01:23,  3.23s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 17%|█▋        | 5/30 [00:23<01:02,  2.49s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 23%|██▎       | 7/30 [00:23<00:28,  1.26s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 27%|██▋       | 8/30 [00:23<00:22,  1.01s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 30%|███       | 9/30 [00:24<00:21,  1.02s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 43%|████▎     | 13/30 [00:42<00:53,  3.16s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 47%|████▋     | 14/30 [00:43<00:44,  2.81s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 50%|█████     | 15/30 [00:49<00:50,  3.38s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 53%|█████▎    | 16/30 [00:50<00:38,  2.75s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 57%|█████▋    | 17/30 [00:50<00:28,  2.23s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 60%|██████    | 18/30 [00:51<00:21,  1.78s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 63%|██████▎   | 19/30 [00:51<00:16,  1.48s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 67%|██████▋   | 20/30 [00:55<00:20,  2.09s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 70%|███████   | 21/30 [00:56<00:15,  1.74s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 77%|███████▋  | 23/30 [00:58<00:10,  1.47s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 80%|████████  | 24/30 [00:59<00:07,  1.27s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 83%|████████▎ | 25/30 [01:05<00:12,  2.49s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 87%|████████▋ | 26/30 [01:05<00:07,  1.95s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 90%|█████████ | 27/30 [01:07<00:05,  1.90s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 93%|█████████▎| 28/30 [01:08<00:03,  1.75s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [01:09<00:00,  2.32s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Fetching 2023-04-21 to 2023-05-20...
This is a large query, it may take a moment to complete

  0%|          | 0/30 [00:00<?, ?it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  3%|▎         | 1/30 [00:22<11:04, 22.93s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  7%|▋         | 2/30 [00:23<04:36,  9.86s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 10%|█         | 3/30 [00:24<02:30,  5.58s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 20%|██        | 6/30 [00:25<00:51,  2.13s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 30%|███       | 9/30 [00:26<00:20,  1.03it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 37%|███▋      | 11/30 [00:27<00:15,  1.23it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 43%|████▎     | 13/30 [00:50<01:15,  4.46s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 50%|█████     | 15/30 [00:51<00:43,  2.90s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 53%|█████▎    | 16/30 [00:52<00:36,  2.60s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 57%|█████▋    | 17/30 [00:53<00:27,  2.10s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 60%|██████    | 18/30 [00:53<00:19,  1.66s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 63%|██████▎   | 19/30 [00:54<00:15,  1.41s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 67%|██████▋   | 20/30 [00:55<00:12,  1.21s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 70%|███████   | 21/30 [00:55<00:08,  1.02it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 77%|███████▋  | 23/30 [00:56<00:05,  1.30it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 80%|████████  | 24/30 [00:58<00:05,  1.04it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 87%|████████▋ | 26/30 [01:06<00:08,  2.05s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 90%|█████████ | 27/30 [01:06<00:04,  1.55s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [01:07<00:00,  2.24s/it]

  Fetching 2023-05-21 to 2023-06-19...
This is a large query, it may take a moment to complete

  0%|          | 0/30 [00:00<?, ?it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  3%|▎         | 1/30 [00:21<10:12, 21.11s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  7%|▋         | 2/30 [00:21<04:16,  9.15s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 10%|█         | 3/30 [00:24<02:44,  6.10s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 30%|███       | 9/30 [00:24<00:24,  1.16s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 37%|███▋      | 11/30 [00:25<00:16,  1.12it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 40%|████      | 12/30 [00:25<00:14,  1.22it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 43%|████▎     | 13/30 [00:47<01:30,  5.34s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 47%|████▋     | 14/30 [00:48<01:08,  4.26s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 50%|█████     | 15/30 [00:49<00:51,  3.42s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 57%|█████▋    | 17/30 [00:50<00:29,  2.25s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 67%|██████▋   | 20/30 [00:51<00:13,  1.32s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 70%|███████   | 21/30 [00:52<00:10,  1.20s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 73%|███████▎  | 22/30 [00:52<00:08,  1.08s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 80%|████████  | 24/30 [00:54<00:05,  1.11it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 83%|████████▎ | 25/30 [01:04<00:14,  2.85s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 87%|████████▋ | 26/30 [01:04<00:09,  2.36s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 90%|█████████ | 27/30 [01:05<00:05,  1.82s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [01:06<00:00,  2.21s/it]

  Fetching 2023-06-20 to 2023-07-19...
This is a large query, it may take a moment to complete

  0%|          | 0/30 [00:00<?, ?it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  3%|▎         | 1/30 [00:21<10:30, 21.75s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 13%|█▎        | 4/30 [00:23<01:25,  3.27s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 17%|█▋        | 5/30 [00:23<00:59,  2.39s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 20%|██        | 6/30 [00:24<00:39,  1.66s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 23%|██▎       | 7/30 [00:24<00:31,  1.39s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 50%|█████     | 15/30 [00:46<00:34,  2.33s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 53%|█████▎    | 16/30 [00:46<00:27,  1.99s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 60%|██████    | 18/30 [00:48<00:17,  1.44s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 73%|███████▎  | 22/30 [00:49<00:05,  1.34it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 87%|████████▋ | 26/30 [01:00<00:06,  1.64s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 90%|█████████ | 27/30 [01:01<00:04,  1.46s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [01:02<00:00,  2.07s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Fetching 2023-07-20 to 2023-08-18...
This is a large query, it may take a moment to complete

  0%|          | 0/30 [00:00<?, ?it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  3%|▎         | 1/30 [00:22<10:52, 22.51s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  7%|▋         | 2/30 [00:23<04:37,  9.90s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 10%|█         | 3/30 [00:24<02:31,  5.60s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 17%|█▋        | 5/30 [00:25<01:10,  2.83s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 20%|██        | 6/30 [00:26<00:53,  2.21s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 23%|██▎       | 7/30 [00:26<00:37,  1.62s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 33%|███▎      | 10/30 [00:27<00:14,  1.36it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 43%|████▎     | 13/30 [00:47<01:09,  4.08s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 47%|████▋     | 14/30 [00:53<01:13,  4.58s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 50%|█████     | 15/30 [00:55<00:57,  3.87s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 53%|█████▎    | 16/30 [00:55<00:41,  2.96s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 57%|█████▋    | 17/30 [00:55<00:29,  2.25s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 60%|██████    | 18/30 [00:56<00:20,  1.75s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 67%|██████▋   | 20/30 [00:57<00:12,  1.24s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 83%|████████▎ | 25/30 [01:05<00:07,  1.51s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 87%|████████▋ | 26/30 [01:09<00:07,  1.96s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 90%|█████████ | 27/30 [01:10<00:05,  1.67s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 97%|█████████▋| 29/30 [01:11<00:01,  1.13s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [01:11<00:00,  2.38s/it]

  Fetching 2023-08-19 to 2023-09-17...
This is a large query, it may take a moment to complete

  0%|          | 0/30 [00:00<?, ?it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  3%|▎         | 1/30 [00:22<10:50, 22.43s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  7%|▋         | 2/30 [00:23<04:34,  9.82s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 10%|█         | 3/30 [00:23<02:28,  5.48s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 13%|█▎        | 4/30 [00:24<01:34,  3.62s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 17%|█▋        | 5/30 [00:25<01:06,  2.66s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 23%|██▎       | 7/30 [00:26<00:30,  1.33s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 27%|██▋       | 8/30 [00:26<00:21,  1.04it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 30%|███       | 9/30 [00:26<00:15,  1.35it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 33%|███▎      | 10/30 [00:27<00:14,  1.36it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 43%|████▎     | 13/30 [00:44<01:01,  3.64s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 47%|████▋     | 14/30 [00:53<01:14,  4.68s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 50%|█████     | 15/30 [00:53<00:55,  3.73s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 53%|█████▎    | 16/30 [00:54<00:41,  2.96s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 60%|██████    | 18/30 [00:55<00:22,  1.87s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 63%|██████▎   | 19/30 [00:55<00:17,  1.61s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 70%|███████   | 21/30 [00:57<00:10,  1.21s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 80%|████████  | 24/30 [00:58<00:05,  1.20it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 83%|████████▎ | 25/30 [01:07<00:11,  2.33s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 87%|████████▋ | 26/30 [01:11<00:10,  2.71s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 90%|█████████ | 27/30 [01:13<00:07,  2.42s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 93%|█████████▎| 28/30 [01:14<00:04,  2.22s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 97%|█████████▋| 29/30 [01:18<00:02,  2.51s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [01:20<00:00,  2.69s/it]

  Fetching 2023-09-18 to 2023-10-17...
This is a large query, it may take a moment to complete

  0%|          | 0/30 [00:00<?, ?it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  3%|▎         | 1/30 [00:22<10:47, 22.31s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  7%|▋         | 2/30 [00:22<04:28,  9.58s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 10%|█         | 3/30 [00:23<02:24,  5.34s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 13%|█▎        | 4/30 [00:23<01:30,  3.50s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 20%|██        | 6/30 [00:24<00:45,  1.90s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 27%|██▋       | 8/30 [00:26<00:29,  1.35s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 37%|███▋      | 11/30 [00:26<00:15,  1.21it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 47%|████▋     | 14/30 [00:50<00:56,  3.54s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 50%|█████     | 15/30 [00:51<00:45,  3.03s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 53%|█████▎    | 16/30 [00:51<00:33,  2.37s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 60%|██████    | 18/30 [00:51<00:17,  1.47s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 77%|███████▋  | 23/30 [00:53<00:05,  1.35it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 83%|████████▎ | 25/30 [01:03<00:12,  2.54s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 90%|█████████ | 27/30 [01:03<00:04,  1.63s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Fetching 2023-10-18 to 2023-11-16...
This is a large query, it may take a moment to complete
Skipping offseason dates

 10%|█         | 3/29 [00:20<02:20,  5.42s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 17%|█▋        | 5/29 [00:21<01:04,  2.70s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 31%|███       | 9/29 [00:21<00:22,  1.11s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 45%|████▍     | 13/29 [00:40<00:55,  3.44s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 52%|█████▏    | 15/29 [00:40<00:33,  2.43s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 66%|██████▌   | 19/29 [00:41<00:13,  1.32s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 29/29 [00:50<00:00,  1.73s/it]

  Fetching 2023-11-17 to 2023-12-16...
This is a large query, it may take a moment to complete

/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

Skipping offseason dates

0it [00:00, ?it/s]

  Fetching 2023-12-17 to 2024-01-15...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  Fetching 2024-01-16 to 2024-02-14...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  Fetching 2024-02-15 to 2024-03-15...
This is a large query, it may take a moment to complete

Skipping offseason dates

  0%|          | 0/1 [00:00<?, ?it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 1/1 [00:01<00:00,  1.68s/it]

  Fetching 2024-03-16 to 2024-04-14...
This is a large query, it may take a moment to complete

  3%|▎         | 1/30 [00:18<09:09, 18.94s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  7%|▋         | 2/30 [00:19<03:55,  8.42s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 10%|█         | 3/30 [00:21<02:21,  5.25s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 17%|█▋        | 5/30 [00:22<01:00,  2.43s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 23%|██▎       | 7/30 [00:22<00:32,  1.43s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 27%|██▋       | 8/30 [00:22<00:25,  1.16s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 30%|███       | 9/30 [00:23<00:22,  1.05s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 33%|███▎      | 10/30 [00:24<00:19,  1.04it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 40%|████      | 12/30 [00:25<00:16,  1.10it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 43%|████▎     | 13/30 [00:31<00:35,  2.07s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 50%|█████     | 15/30 [00:46<01:09,  4.62s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 60%|██████    | 18/30 [00:47<00:28,  2.34s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 63%|██████▎   | 19/30 [00:48<00:21,  1.98s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 67%|██████▋   | 20/30 [00:48<00:16,  1.63s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 73%|███████▎  | 22/30 [00:49<00:08,  1.12s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 77%|███████▋  | 23/30 [00:50<00:08,  1.20s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 80%|████████  | 24/30 [00:53<00:09,  1.64s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 83%|████████▎ | 25/30 [00:55<00:08,  1.70s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 87%|████████▋ | 26/30 [00:58<00:08,  2.01s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 90%|█████████ | 27/30 [00:59<00:05,  1.69s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 93%|█████████▎| 28/30 [00:59<00:02,  1.40s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [01:00<00:00,  2.02s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Fetching 2024-04-15 to 2024-05-14...
This is a large query, it may take a moment to complete

  0%|          | 0/30 [00:00<?, ?it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  3%|▎         | 1/30 [00:23<11:07, 23.01s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  7%|▋         | 2/30 [00:23<04:30,  9.68s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 13%|█▎        | 4/30 [00:24<01:39,  3.82s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 17%|█▋        | 5/30 [00:24<01:09,  2.76s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 20%|██        | 6/30 [00:24<00:50,  2.09s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 27%|██▋       | 8/30 [00:26<00:31,  1.41s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 57%|█████▋    | 17/30 [00:47<00:25,  2.00s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 67%|██████▋   | 20/30 [00:48<00:13,  1.38s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [00:58<00:00,  1.96s/it]

  Fetching 2024-05-15 to 2024-06-13...
This is a large query, it may take a moment to complete

  0%|          | 0/30 [00:00<?, ?it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  3%|▎         | 1/30 [00:22<10:59, 22.76s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  7%|▋         | 2/30 [00:23<04:28,  9.60s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 17%|█▋        | 5/30 [00:24<01:04,  2.56s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 30%|███       | 9/30 [00:26<00:18,  1.13it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 40%|████      | 12/30 [00:26<00:09,  1.89it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 43%|████▎     | 13/30 [00:48<01:19,  4.68s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 47%|████▋     | 14/30 [00:49<00:59,  3.75s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 50%|█████     | 15/30 [00:49<00:44,  2.97s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 57%|█████▋    | 17/30 [00:50<00:23,  1.77s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 60%|██████    | 18/30 [00:52<00:21,  1.82s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 63%|██████▎   | 19/30 [00:53<00:18,  1.70s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 67%|██████▋   | 20/30 [00:54<00:13,  1.39s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 70%|███████   | 21/30 [00:54<00:10,  1.15s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 73%|███████▎  | 22/30 [00:55<00:07,  1.03it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 77%|███████▋  | 23/30 [00:56<00:07,  1.05s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 83%|████████▎ | 25/30 [01:07<00:15,  3.05s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 87%|████████▋ | 26/30 [01:10<00:12,  3.12s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 90%|█████████ | 27/30 [01:11<00:07,  2.39s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [01:12<00:00,  2.40s/it]

  Fetching 2024-06-14 to 2024-07-13...
This is a large query, it may take a moment to complete

  0%|          | 0/30 [00:00<?, ?it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  7%|▋         | 2/30 [00:25<04:55, 10.57s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 13%|█▎        | 4/30 [00:27<01:43,  3.99s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 17%|█▋        | 5/30 [00:27<01:07,  2.71s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 20%|██        | 6/30 [00:28<00:46,  1.92s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 23%|██▎       | 7/30 [00:28<00:35,  1.55s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 30%|███       | 9/30 [00:29<00:19,  1.09it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 33%|███▎      | 10/30 [00:29<00:15,  1.26it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 37%|███▋      | 11/30 [00:30<00:15,  1.23it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 43%|████▎     | 13/30 [00:51<01:24,  4.99s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 47%|████▋     | 14/30 [00:54<01:10,  4.43s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 50%|█████     | 15/30 [00:55<00:52,  3.51s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 53%|█████▎    | 16/30 [00:55<00:39,  2.80s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 57%|█████▋    | 17/30 [00:56<00:28,  2.17s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 60%|██████    | 18/30 [00:57<00:22,  1.88s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 63%|██████▎   | 19/30 [00:58<00:16,  1.51s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 67%|██████▋   | 20/30 [00:58<00:12,  1.25s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 70%|███████   | 21/30 [01:00<00:12,  1.36s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 73%|███████▎  | 22/30 [01:01<00:09,  1.21s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 77%|███████▋  | 23/30 [01:05<00:15,  2.15s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 80%|████████  | 24/30 [01:06<00:11,  1.91s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 83%|████████▎ | 25/30 [01:15<00:19,  3.99s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 87%|████████▋ | 26/30 [01:17<00:13,  3.33s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 90%|█████████ | 27/30 [01:18<00:07,  2.55s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 97%|█████████▋| 29/30 [01:20<00:01,  1.76s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [01:22<00:00,  2.74s/it]

  Fetching 2024-07-14 to 2024-08-12...
This is a large query, it may take a moment to complete

 10%|█         | 3/30 [00:22<02:39,  5.91s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 17%|█▋        | 5/30 [00:26<01:35,  3.83s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 20%|██        | 6/30 [00:28<01:19,  3.31s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 23%|██▎       | 7/30 [00:28<00:57,  2.51s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 27%|██▋       | 8/30 [00:29<00:45,  2.08s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 33%|███▎      | 10/30 [00:30<00:24,  1.21s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 37%|███▋      | 11/30 [00:31<00:20,  1.09s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 43%|████▎     | 13/30 [00:45<01:04,  3.81s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 47%|████▋     | 14/30 [00:45<00:48,  3.01s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 53%|█████▎    | 16/30 [00:47<00:26,  1.90s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 57%|█████▋    | 17/30 [00:52<00:36,  2.81s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 60%|██████    | 18/30 [00:58<00:43,  3.66s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 63%|██████▎   | 19/30 [00:58<00:29,  2.67s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 67%|██████▋   | 20/30 [01:01<00:27,  2.71s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 70%|███████   | 21/30 [01:01<00:18,  2.09s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 73%|███████▎  | 22/30 [01:02<00:12,  1.59s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 77%|███████▋  | 23/30 [01:02<00:08,  1.24s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 80%|████████  | 24/30 [01:03<00:06,  1.13s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 83%|████████▎ | 25/30 [01:09<00:13,  2.61s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 87%|████████▋ | 26/30 [01:09<00:07,  1.91s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 90%|█████████ | 27/30 [01:10<00:04,  1.55s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 97%|█████████▋| 29/30 [01:11<00:01,  1.10s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [01:12<00:00,  2.40s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Fetching 2024-08-13 to 2024-09-11...
This is a large query, it may take a moment to complete

  0%|          | 0/30 [00:00<?, ?it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  3%|▎         | 1/30 [00:24<12:00, 24.84s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  7%|▋         | 2/30 [00:26<05:13, 11.19s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 20%|██        | 6/30 [00:28<00:56,  2.36s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 23%|██▎       | 7/30 [00:29<00:45,  2.00s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 33%|███▎      | 10/30 [00:31<00:21,  1.08s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 43%|████▎     | 13/30 [00:51<01:01,  3.61s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 47%|████▋     | 14/30 [00:58<01:06,  4.18s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 50%|█████     | 15/30 [00:59<00:52,  3.53s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 53%|█████▎    | 16/30 [00:59<00:41,  2.94s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 60%|██████    | 18/30 [01:01<00:23,  1.95s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 63%|██████▎   | 19/30 [01:01<00:17,  1.55s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 67%|██████▋   | 20/30 [01:04<00:17,  1.72s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 70%|███████   | 21/30 [01:04<00:12,  1.34s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 73%|███████▎  | 22/30 [01:05<00:08,  1.12s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 77%|███████▋  | 23/30 [01:05<00:06,  1.09it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 83%|████████▎ | 25/30 [01:09<00:06,  1.28s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 87%|████████▋ | 26/30 [01:12<00:07,  1.80s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 90%|█████████ | 27/30 [01:12<00:04,  1.41s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 93%|█████████▎| 28/30 [01:14<00:02,  1.47s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 97%|█████████▋| 29/30 [01:14<00:01,  1.14s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [01:16<00:00,  2.54s/it]

  Fetching 2024-09-12 to 2024-10-11...
This is a large query, it may take a moment to complete

  0%|          | 0/30 [00:00<?, ?it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  3%|▎         | 1/30 [00:24<11:41, 24.18s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  7%|▋         | 2/30 [00:26<05:14, 11.24s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 10%|█         | 3/30 [00:27<02:58,  6.63s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 13%|█▎        | 4/30 [00:28<01:50,  4.25s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 17%|█▋        | 5/30 [00:29<01:22,  3.31s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 20%|██        | 6/30 [00:30<00:56,  2.35s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 23%|██▎       | 7/30 [00:30<00:40,  1.76s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 27%|██▋       | 8/30 [00:31<00:30,  1.38s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 30%|███       | 9/30 [00:32<00:27,  1.29s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 33%|███▎      | 10/30 [00:33<00:27,  1.36s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 37%|███▋      | 11/30 [00:35<00:24,  1.28s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 40%|████      | 12/30 [00:35<00:18,  1.03s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 43%|████▎     | 13/30 [00:39<00:31,  1.87s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 47%|████▋     | 14/30 [00:48<01:03,  3.99s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 50%|█████     | 15/30 [00:49<00:47,  3.15s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 53%|█████▎    | 16/30 [00:53<00:47,  3.38s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 57%|█████▋    | 17/30 [00:57<00:48,  3.70s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 60%|██████    | 18/30 [00:58<00:35,  2.93s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 63%|██████▎   | 19/30 [00:59<00:23,  2.10s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 70%|███████   | 21/30 [00:59<00:10,  1.18s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 73%|███████▎  | 22/30 [01:01<00:11,  1.42s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 77%|███████▋  | 23/30 [01:03<00:10,  1.50s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 80%|████████  | 24/30 [01:03<00:07,  1.20s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 83%|████████▎ | 25/30 [01:04<00:04,  1.01it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 87%|████████▋ | 26/30 [01:07<00:06,  1.56s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 90%|█████████ | 27/30 [01:07<00:03,  1.18s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 93%|█████████▎| 28/30 [01:07<00:01,  1.15it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 97%|█████████▋| 29/30 [01:07<00:00,  1.36it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [01:08<00:00,  2.29s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Fetching 2024-10-12 to 2024-11-10...
This is a large query, it may take a moment to complete

  7%|▋         | 2/30 [00:24<04:40, 10.02s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 13%|█▎        | 4/30 [00:24<01:39,  3.83s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 17%|█▋        | 5/30 [00:24<01:07,  2.68s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 20%|██        | 6/30 [00:24<00:46,  1.94s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 33%|███▎      | 10/30 [00:25<00:15,  1.27it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 37%|███▋      | 11/30 [00:25<00:12,  1.51it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 47%|████▋     | 14/30 [00:49<01:21,  5.08s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 50%|█████     | 15/30 [00:50<00:59,  3.94s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 67%|██████▋   | 20/30 [00:51<00:11,  1.20s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 73%|███████▎  | 22/30 [00:52<00:07,  1.11it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 77%|███████▋  | 23/30 [00:53<00:05,  1.29it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Fetching 2024-11-11 to 2024-12-10...
This is a large query, it may take a moment to complete
Skipping offseason dates

100%|██████████| 5/5 [00:09<00:00,  1.90s/it]

  Fetching 2024-12-11 to 2025-01-09...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  Fetching 2025-01-10 to 2025-02-08...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  Fetching 2025-02-09 to 2025-03-10...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  Fetching 2025-03-11 to 2025-04-09...
This is a large query, it may take a moment to complete

Skipping offseason dates

  4%|▍         | 1/26 [00:21<08:55, 21.43s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  8%|▊         | 2/26 [00:22<03:43,  9.32s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 12%|█▏        | 3/26 [00:22<02:03,  5.37s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 19%|█▉        | 5/26 [00:24<00:51,  2.45s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 27%|██▋       | 7/26 [00:25<00:27,  1.43s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 31%|███       | 8/26 [00:25<00:21,  1.20s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 35%|███▍      | 9/26 [00:27<00:22,  1.34s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 38%|███▊      | 10/26 [00:28<00:19,  1.24s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 42%|████▏     | 11/26 [00:28<00:15,  1.04s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 92%|█████████▏| 24/26 [00:55<00:01,  1.37it/s]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 96%|█████████▌| 25/26 [00:59<00:01,  1.47s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 26/26 [00:59<00:00,  2.31s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Fetching 2025-04-10 to 2025-05-09...
This is a large query, it may take a moment to complete

 30%|███       | 9/30 [00:21<00:36,  1.73s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [00:55<00:00,  1.85s/it]

  Fetching 2025-05-10 to 2025-06-08...
This is a large query, it may take a moment to complete

 87%|████████▋ | 26/30 [00:51<00:07,  1.79s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [00:58<00:00,  1.94s/it]

  Fetching 2025-06-09 to 2025-07-08...
This is a large query, it may take a moment to complete

 20%|██        | 6/30 [00:19<00:58,  2.44s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 37%|███▋      | 11/30 [00:27<00:36,  1.92s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [00:56<00:00,  1.88s/it]

  Fetching 2025-07-09 to 2025-08-07...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:51<00:00,  1.72s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Fetching 2025-08-08 to 2025-09-06...
This is a large query, it may take a moment to complete

 47%|████▋     | 14/30 [00:43<00:49,  3.11s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 30/30 [00:55<00:00,  1.83s/it]

  Fetching 2025-09-07 to 2025-10-06...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:52<00:00,  1.76s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Fetching 2025-10-07 to 2025-11-05...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:53<00:00,  1.77s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Fetching 2025-11-06 to 2025-12-05...
This is a large query, it may take a moment to complete
Skipping offseason dates

100%|██████████| 10/10 [00:16<00:00,  1.65s/it]

  Fetching 2025-12-06 to 2026-01-04...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  Fetching 2026-01-05 to 2026-02-03...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  Fetching 2026-02-04 to 2026-03-05...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  Fetching 2026-03-06 to 2026-03-31...
This is a large query, it may take a moment to complete

Skipping offseason dates

 53%|█████▎    | 9/17 [00:20<00:10,  1.31s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 76%|███████▋  | 13/17 [00:30<00:06,  1.73s/it]/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/datahelpers/postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
100%|██████████| 17/17 [00:31<00:00,  1.83s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Found 26067 pitcher game logs
Shape: (26067, 18)
Date range: 2021-04-01 00:00:00 to 2026-03-30 00:00:00

,game_date,game_pk,pitcher_id,Name,team_abbrev,opp_abbrev,home_team,away_team,pitches,SO,BB,H,HR,HBP,swinging_strikes,called_strikes,is_home,swstr_pct
0,2021-04-01,634615,477132,"Kershaw, Clayton",LAD,COL,COL,LAD,77,2,1,10,0,0,6,11,0,0.077922
1,2021-04-01,634615,608566,"Márquez, Germán",COL,LAD,COL,LAD,92,2,6,6,0,0,5,15,1,0.054348
2,2021-04-01,634618,506433,"Darvish, Yu",SD,AZ,SD,AZ,93,6,1,8,2,0,8,19,1,0.086022
3,2021-04-01,634618,518516,"Bumgarner, Madison",AZ,SD,SD,AZ,91,6,3,7,2,1,14,19,0,0.153846
4,2021-04-01,634622,605400,"Nola, Aaron",PHI,ATL,PHI,ATL,84,6,0,6,1,0,7,16,1,0.083333
5,2021-04-01,634622,608331,"Fried, Max",ATL,PHI,PHI,ATL,94,8,2,6,0,1,17,13,0,0.180851
6,2021-04-01,634625,592332,"Gausman, Kevin",SF,SEA,SEA,SF,90,6,2,2,0,0,11,18,0,0.122222
7,2021-04-01,634625,594835,"Gonzales, Marco",SEA,SF,SEA,SF,99,2,2,8,3,0,4,17,1,0.040404
8,2021-04-01,634630,621368,"Hearn, Taylor",TEX,KC,KC,TEX,50,2,1,4,1,0,5,7,0,0.1
9,2021-04-01,634630,641745,"Keller, Brad",KC,TEX,KC,TEX,51,0,2,9,0,0,2,11,1,0.039216

In [ ]:
# Available columns
print("Pitcher game log columns:")
print(pitcher_games.columns.tolist())

Pitcher game log columns:
['game_date', 'game_pk', 'pitcher_id', 'Name', 'team_abbrev', 'opp_abbrev', 'home_team', 'away_team', 'pitches', 'SO', 'BB', 'H', 'HR', 'HBP', 'swinging_strikes', 'called_strikes', 'is_home', 'swstr_pct']

In [ ]:
# Verify accurate team identification
# No more ambiguous city names - we can distinguish NYY from NYM, CHC from CHW, etc.

print("Unique teams in data:")
print(sorted(pitcher_games['team_abbrev'].unique()))

print("\nGames by team:")
pitcher_games['team_abbrev'].value_counts().head(10)

Unique teams in data:
['ATH', 'ATL', 'AZ', 'BAL', 'BOS', 'CHC', 'CIN', 'CLE', 'COL', 'CWS', 'DET', 'HOU', 'KC', 'LAA', 'LAD', 'MIA', 'MIL', 'MIN', 'NYM', 'NYY', 'PHI', 'PIT', 'SD', 'SEA', 'SF', 'STL', 'TB', 'TEX', 'TOR', 'WSH']

Games by team:

team_abbrev
LAD    905
HOU    902
PHI    900
NYY    888
AZ     885
SEA    881
MIL    881
TEX    880
ATL    877
SD     875
Name: count, dtype: int64

In [ ]:
# Strikeout distribution (our target variable)
print("Strikeout statistics:")
print(pitcher_games['SO'].describe())

print("\nStrikeout distribution:")
pitcher_games['SO'].value_counts().sort_index()

Strikeout statistics:
count    26067.000000
mean         4.768903
std          2.501545
min          0.000000
25%          3.000000
50%          5.000000
75%          6.000000
max         16.000000
Name: SO, dtype: float64

Strikeout distribution:

SO
0      579
1     1562
2     2813
3     3723
4     4096
5     3949
6     3280
7     2378
8     1635
9      977
10     564
11     274
12     148
13      58
14      25
15       4
16       2
Name: count, dtype: int64

## Pitcher Season Stats

Season-level pitching statistics from FanGraphs. Useful for baseline pitcher quality metrics.

In [ ]:
# Collect pitcher season stats for all seasons
pitcher_season_list = []
for season in SEASONS:
    print(f"Fetching pitcher season stats for {season}...")
    df = get_pitcher_season_stats(season, qual=0)
    df['season'] = season
    pitcher_season_list.append(df)

pitcher_season = pd.concat(pitcher_season_list, ignore_index=True)
print(f"\nTotal shape: {pitcher_season.shape}")
pitcher_season.head(10)

Fetching pitcher season stats for 2021...
Fetching pitcher season stats for 2021...
Fetching pitcher season stats for 2022...
Fetching pitcher season stats for 2022...
Fetching pitcher season stats for 2023...
Fetching pitcher season stats for 2023...
Fetching pitcher season stats for 2024...
Fetching pitcher season stats for 2024...

Total shape: (3498, 68)

,Name,Team,W,L,ERA,G,GS,IP,TBF,H,R,ER,HR,BB,SO,K/9,BB/9,K/BB,H/9,HR/9,AVG,WHIP,BABIP,LOB%,FIP,...,Soft%,Med%,Hard%,FBv,SL%,SLv,CB%,CBv,CH%,CHv,wFB,wSL,wCB,wCH,wFB/C,wSL/C,wCB/C,wCH/C,CStr%,CSW%,xERA,EV,Barrel%,HardHit%,season
0,Corbin Burnes,MIL,11,5,2.43,28,28,167.0,657,123,47,45,7,34,234,12.61,1.83,6.88,6.63,0.38,0.199,0.94,0.309,0.757,1.63,...,0.204,0.548,0.248,96.9,0.090,88.1,0.184,81.3,0.098,90.7,-2.4,7.0,13.3,0.7,-0.85,2.99,2.79,0.27,0.172,0.338,2.04,85.5,0.031,0.305,2021
1,Zack Wheeler,PHI,14,10,2.78,32,32,213.1,849,169,72,66,16,46,247,10.42,1.94,5.37,7.13,0.68,0.213,1.01,0.288,0.753,2.59,...,0.230,0.546,0.224,97.1,0.249,91.6,0.107,81.5,0.032,90.4,26.0,12.6,2.5,-0.2,1.33,1.58,0.72,-0.15,0.156,0.280,2.79,84.6,0.046,0.285,2021
2,Nathan Eovaldi,BOS,11,9,3.75,32,32,182.1,764,182,81,76,15,35,195,9.63,1.73,5.57,8.98,0.74,0.252,1.19,0.326,0.704,2.79,...,0.167,0.562,0.271,96.9,0.137,85.8,0.188,78.6,NaN,NaN,0.1,0.3,6.9,NaN,0.01,0.07,1.26,NaN,0.173,0.299,3.41,88.0,0.063,0.364,2021
3,Walker Buehler,LAD,16,4,2.47,33,33,207.2,815,149,61,57,19,52,212,9.19,2.25,4.08,6.46,0.82,0.197,0.97,0.247,0.809,3.16,...,0.174,0.519,0.306,95.4,0.145,85.1,0.132,80.2,0.049,91.5,22.9,5.9,2.3,4.6,1.40,1.29,0.55,3.01,0.181,0.296,3.08,88.2,0.068,0.371,2021
4,Max Scherzer,- - -,15,4,2.46,30,30,179.1,693,119,53,49,23,36,236,11.84,1.81,6.56,5.97,1.15,0.184,0.86,0.247,0.843,2.97,...,0.170,0.484,0.345,94.3,0.191,85.9,0.098,76.9,0.149,85.0,19.9,13.2,-0.2,5.8,1.51,2.45,-0.09,1.38,0.157,0.316,2.87,87.9,0.080,0.343,2021
5,Gerrit Cole,NYY,16,8,3.23,30,30,181.1,726,151,69,65,24,41,243,12.06,2.03,5.93,7.49,1.19,0.221,1.06,0.305,0.779,2.92,...,0.186,0.500,0.314,97.7,0.222,88.4,0.157,83.5,0.142,89.9,12.1,10.3,-2.3,5.9,0.85,1.57,-0.50,1.40,0.176,0.321,3.08,88.7,0.098,0.386,2021
6,Julio Urias,LAD,20,3,2.96,32,32,185.2,745,151,67,61,19,38,195,9.45,1.84,5.13,7.32,0.92,0.216,1.02,0.272,0.762,3.13,...,0.208,0.517,0.275,94.1,NaN,NaN,0.342,81.4,0.173,86.9,-0.4,NaN,23.1,7.9,-0.03,NaN,2.43,1.63,0.186,0.298,3.14,86.0,0.053,0.303,2021
7,Carlos Rodon,CHW,13,5,2.37,24,24,132.2,534,91,39,35,13,36,185,12.55,2.44,5.14,6.17,0.88,0.186,0.96,0.267,0.822,2.65,...,0.201,0.523,0.276,95.4,0.272,85.8,0.017,76.8,0.124,85.3,22.6,13.0,-2.2,-6.3,1.74,2.15,-5.84,-2.29,0.154,0.303,2.68,89.2,0.066,0.361,2021
8,Jacob deGrom,NYM,7,2,1.08,15,15,92.0,324,40,14,11,6,11,146,14.28,1.08,13.27,3.91,0.59,0.128,0.55,0.213,0.872,1.24,...,0.211,0.482,0.307,99.3,0.334,91.6,0.003,83.5,0.089,91.4,17.7,16.0,0.4,3.1,2.51,3.92,10.44,2.88,0.142,0.358,1.56,87.7,0.066,0.367,2021
9,Kevin Gausman,SFG,14,6,2.81,33,33,192.0,775,150,66,60,20,50,227,10.64,2.34,4.54,7.03,0.94,0.208,1.04,0.274,0.784,3.00,...,0.162,0.496,0.342,94.6,0.056,82.0,NaN,NaN,0.051,84.0,11.5,0.2,NaN,-1.1,0.73,0.14,NaN,-0.74,0.157,0.310,3.57,89.1,0.071,0.409,2021

In [ ]:
# Available columns
print("Pitcher season stats columns:")
print(pitcher_season.columns.tolist())

Pitcher season stats columns:
['Name', 'Team', 'W', 'L', 'ERA', 'G', 'GS', 'IP', 'TBF', 'H', 'R', 'ER', 'HR', 'BB', 'SO', 'K/9', 'BB/9', 'K/BB', 'H/9', 'HR/9', 'AVG', 'WHIP', 'BABIP', 'LOB%', 'FIP', 'xFIP', 'SIERA', 'GB%', 'FB%', 'LD%', 'HR/FB', 'K%', 'BB%', 'K-BB%', 'O-Swing%', 'Z-Swing%', 'Swing%', 'O-Contact%', 'Z-Contact%', 'Contact%', 'Zone%', 'F-Strike%', 'SwStr%', 'Soft%', 'Med%', 'Hard%', 'FBv', 'SL%', 'SLv', 'CB%', 'CBv', 'CH%', 'CHv', 'wFB', 'wSL', 'wCB', 'wCH', 'wFB/C', 'wSL/C', 'wCB/C', 'wCH/C', 'CStr%', 'CSW%', 'xERA', 'EV', 'Barrel%', 'HardHit%', 'season']

## Statcast Pitch Data

Raw pitch-by-pitch data from Statcast. This is the core dataset for building matchup features.

**Warning**: This is a large query (~1M+ rows per season). It will take several minutes.

In [ ]:
# Collect Statcast pitch-level data
# This is the largest dataset - may take 10+ minutes for multiple seasons

pitches = get_statcast_pitches(
    start_date=DATA_START,
    end_date=DATA_END,
)

print(f"Shape: {pitches.shape}")
print(f"Date range: {pitches['game_date'].min()} to {pitches['game_date'].max()}")
print(f"Unique pitchers: {pitches['pitcher'].nunique():,}")
print(f"Unique batters: {pitches['batter'].nunique():,}")
pitches.head()

clear_mem()

Fetching Statcast pitches from 2021-04-01 to 2026-03-31...
  2021-04-01 to 2021-04-14...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:23<00:00,  1.68s/it]

  2021-04-15 to 2021-04-28...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:26<00:00,  1.87s/it]

  2021-04-29 to 2021-05-12...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:30<00:00,  2.19s/it]

  2021-05-13 to 2021-05-26...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:23<00:00,  1.66s/it]

  2021-05-27 to 2021-06-09...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.53s/it]

  2021-06-10 to 2021-06-23...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.55s/it]

  2021-06-24 to 2021-07-07...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.54s/it]

  2021-07-08 to 2021-07-21...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.56s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  2021-07-22 to 2021-08-04...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.54s/it]

  2021-08-05 to 2021-08-18...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.55s/it]

  2021-08-19 to 2021-09-01...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.55s/it]

  2021-09-02 to 2021-09-15...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.52s/it]

  2021-09-16 to 2021-09-29...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.59s/it]

  2021-09-30 to 2021-10-13...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.59s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  2021-10-14 to 2021-10-27...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.59s/it]

  2021-10-28 to 2021-11-10...
This is a large query, it may take a moment to complete

/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)
100%|██████████| 14/14 [00:22<00:00,  1.57s/it]

  2021-11-11 to 2021-11-24...
This is a large query, it may take a moment to complete

/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

Skipping offseason dates

100%|██████████| 5/5 [00:08<00:00,  1.62s/it]

  2021-11-25 to 2021-12-08...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2021-12-09 to 2021-12-22...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2021-12-23 to 2022-01-05...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2022-01-06 to 2022-01-19...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2022-01-20 to 2022-02-02...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2022-02-03 to 2022-02-16...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2022-02-17 to 2022-03-02...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2022-03-03 to 2022-03-16...
This is a large query, it may take a moment to complete

Skipping offseason dates

100%|██████████| 2/2 [00:03<00:00,  1.57s/it]

  2022-03-17 to 2022-03-30...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.57s/it]

  2022-03-31 to 2022-04-13...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.59s/it]

  2022-04-14 to 2022-04-27...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.56s/it]

  2022-04-28 to 2022-05-11...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.64s/it]

  2022-05-12 to 2022-05-25...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.60s/it]

  2022-05-26 to 2022-06-08...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.57s/it]

  2022-06-09 to 2022-06-22...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.56s/it]

  2022-06-23 to 2022-07-06...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.54s/it]

  2022-07-07 to 2022-07-20...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.59s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  2022-07-21 to 2022-08-03...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.63s/it]

  2022-08-04 to 2022-08-17...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:23<00:00,  1.70s/it]

  2022-08-18 to 2022-08-31...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.55s/it]

  2022-09-01 to 2022-09-14...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.58s/it]

  2022-09-15 to 2022-09-28...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.55s/it]

  2022-09-29 to 2022-10-12...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.60s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  2022-10-13 to 2022-10-26...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:23<00:00,  1.67s/it]

  2022-10-27 to 2022-11-09...
This is a large query, it may take a moment to complete

/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)
100%|██████████| 14/14 [00:23<00:00,  1.68s/it]

  2022-11-10 to 2022-11-23...
This is a large query, it may take a moment to complete

/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

Skipping offseason dates

100%|██████████| 6/6 [00:09<00:00,  1.63s/it]

  2022-11-24 to 2022-12-07...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2022-12-08 to 2022-12-21...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2022-12-22 to 2023-01-04...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2023-01-05 to 2023-01-18...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2023-01-19 to 2023-02-01...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2023-02-02 to 2023-02-15...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2023-02-16 to 2023-03-01...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2023-03-02 to 2023-03-15...
This is a large query, it may take a moment to complete

Skipping offseason dates

100%|██████████| 1/1 [00:01<00:00,  1.05s/it]

  2023-03-16 to 2023-03-29...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:23<00:00,  1.66s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  2023-03-30 to 2023-04-12...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.56s/it]

  2023-04-13 to 2023-04-26...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.53s/it]

  2023-04-27 to 2023-05-10...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:24<00:00,  1.74s/it]

  2023-05-11 to 2023-05-24...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:23<00:00,  1.66s/it]

  2023-05-25 to 2023-06-07...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.59s/it]

  2023-06-08 to 2023-06-21...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.60s/it]

  2023-06-22 to 2023-07-05...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:23<00:00,  1.70s/it]

  2023-07-06 to 2023-07-19...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:24<00:00,  1.73s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  2023-07-20 to 2023-08-02...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.62s/it]

  2023-08-03 to 2023-08-16...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.60s/it]

  2023-08-17 to 2023-08-30...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.63s/it]

  2023-08-31 to 2023-09-13...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:23<00:00,  1.66s/it]

  2023-09-14 to 2023-09-27...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.63s/it]

  2023-09-28 to 2023-10-11...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.59s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  2023-10-12 to 2023-10-25...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.64s/it]

  2023-10-26 to 2023-11-08...
This is a large query, it may take a moment to complete

/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)
100%|██████████| 14/14 [00:22<00:00,  1.60s/it]

  2023-11-09 to 2023-11-22...
This is a large query, it may take a moment to complete

/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

Skipping offseason dates

100%|██████████| 7/7 [00:12<00:00,  1.75s/it]

  2023-11-23 to 2023-12-06...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2023-12-07 to 2023-12-20...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2023-12-21 to 2024-01-03...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2024-01-04 to 2024-01-17...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2024-01-18 to 2024-01-31...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2024-02-01 to 2024-02-14...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2024-02-15 to 2024-02-28...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2024-02-29 to 2024-03-13...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2024-03-14 to 2024-03-27...
This is a large query, it may take a moment to complete

Skipping offseason dates

100%|██████████| 13/13 [00:21<00:00,  1.69s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  2024-03-28 to 2024-04-10...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.58s/it]

  2024-04-11 to 2024-04-24...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:24<00:00,  1.73s/it]

  2024-04-25 to 2024-05-08...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.56s/it]

  2024-05-09 to 2024-05-22...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:23<00:00,  1.70s/it]

  2024-05-23 to 2024-06-05...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.55s/it]

  2024-06-06 to 2024-06-19...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.58s/it]

  2024-06-20 to 2024-07-03...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.63s/it]

  2024-07-04 to 2024-07-17...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:24<00:00,  1.72s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  2024-07-18 to 2024-07-31...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.61s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  2024-08-01 to 2024-08-14...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:22<00:00,  1.59s/it]

  2024-08-15 to 2024-08-28...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.56s/it]

  2024-08-29 to 2024-09-11...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:24<00:00,  1.77s/it]

  2024-09-12 to 2024-09-25...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:21<00:00,  1.56s/it]

  2024-09-26 to 2024-10-09...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:27<00:00,  1.99s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  2024-10-10 to 2024-10-23...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:24<00:00,  1.73s/it]

  2024-10-24 to 2024-11-06...
This is a large query, it may take a moment to complete

/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)
100%|██████████| 14/14 [00:22<00:00,  1.64s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  2024-11-07 to 2024-11-20...
This is a large query, it may take a moment to complete
Skipping offseason dates

100%|██████████| 9/9 [00:15<00:00,  1.70s/it]

  2024-11-21 to 2024-12-04...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2024-12-05 to 2024-12-18...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2024-12-19 to 2025-01-01...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2025-01-02 to 2025-01-15...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2025-01-16 to 2025-01-29...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2025-01-30 to 2025-02-12...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2025-02-13 to 2025-02-26...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2025-02-27 to 2025-03-12...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2025-03-13 to 2025-03-26...
This is a large query, it may take a moment to complete

Skipping offseason dates

100%|██████████| 12/12 [00:21<00:00,  1.77s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  2025-03-27 to 2025-04-09...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:27<00:00,  1.98s/it]

  2025-04-10 to 2025-04-23...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:26<00:00,  1.86s/it]

  2025-04-24 to 2025-05-07...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:23<00:00,  1.70s/it]

  2025-05-08 to 2025-05-21...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:27<00:00,  2.00s/it]

  2025-05-22 to 2025-06-04...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:24<00:00,  1.78s/it]

  2025-06-05 to 2025-06-18...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:25<00:00,  1.85s/it]

  2025-06-19 to 2025-07-02...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:29<00:00,  2.12s/it]

  2025-07-03 to 2025-07-16...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:26<00:00,  1.89s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  2025-07-17 to 2025-07-30...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:24<00:00,  1.77s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  2025-07-31 to 2025-08-13...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:28<00:00,  2.03s/it]

  2025-08-14 to 2025-08-27...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:24<00:00,  1.75s/it]

  2025-08-28 to 2025-09-10...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:26<00:00,  1.86s/it]

  2025-09-11 to 2025-09-24...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:29<00:00,  2.10s/it]

  2025-09-25 to 2025-10-08...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:25<00:00,  1.84s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  2025-10-09 to 2025-10-22...
This is a large query, it may take a moment to complete

100%|██████████| 14/14 [00:25<00:00,  1.84s/it]

  2025-10-23 to 2025-11-05...
This is a large query, it may take a moment to complete

/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)
100%|██████████| 14/14 [00:29<00:00,  2.08s/it]

  2025-11-06 to 2025-11-19...
This is a large query, it may take a moment to complete

/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

Skipping offseason dates

100%|██████████| 10/10 [00:20<00:00,  2.01s/it]

  2025-11-20 to 2025-12-03...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2025-12-04 to 2025-12-17...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2025-12-18 to 2025-12-31...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2026-01-01 to 2026-01-14...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2026-01-15 to 2026-01-28...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2026-01-29 to 2026-02-11...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2026-02-12 to 2026-02-25...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2026-02-26 to 2026-03-11...
This is a large query, it may take a moment to complete

Skipping offseason dates

0it [00:00, ?it/s]

  2026-03-12 to 2026-03-25...
This is a large query, it may take a moment to complete

Skipping offseason dates

100%|██████████| 11/11 [00:20<00:00,  1.86s/it]

  2026-03-26 to 2026-03-31...
This is a large query, it may take a moment to complete

100%|██████████| 6/6 [00:12<00:00,  2.01s/it]
/Applications/miniconda3/envs/mlbenv/lib/python3.13/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Total pitches: 3,860,179
Shape: (3860179, 118)
Date range: 2021-04-01 00:00:00 to 2026-03-30 00:00:00
Unique pitchers: 2,803
Unique batters: 3,490

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,spin_dir,spin_rate_deprecated,break_angle_deprecated,break_length_deprecated,zone,des,game_type,stand,p_throws,home_team,away_team,type,hit_location,bb_type,balls,...,delta_pitcher_run_exp,hyper_speed,home_score_diff,bat_score_diff,home_win_exp,bat_win_exp,age_pit_legacy,age_bat_legacy,age_pit,age_bat,n_thruorder_pitcher,n_priorpa_thisgame_player_at_bat,pitcher_days_since_prev_game,batter_days_since_prev_game,pitcher_days_until_next_game,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
0,SL,2021-04-14,83.6,-1.6,6.17,"Jansen, Kenley",606132,445276,strikeout,swinging_strike_blocked,<NA>,<NA>,<NA>,<NA>,13,"Raimel Tapia strikes out swinging, catcher Aus...",R,L,R,LAD,COL,S,2,None,0,...,0.168,<NA>,2,-2,0.975,0.025,33,27,34,27,1,4,3,1,2,1,3.43,-0.85,0.85,67.7,<NA>,<NA>,<NA>,<NA>,<NA>
1,FC,2021-04-14,93.6,-1.73,6.27,"Jansen, Kenley",606132,445276,None,foul,<NA>,<NA>,<NA>,<NA>,11,Foul,R,L,R,LAD,COL,S,<NA>,None,0,...,0.0,88.0,2,-2,0.975,0.025,33,27,34,27,1,4,3,1,2,1,0.99,-0.48,0.48,66.9,<NA>,<NA>,<NA>,<NA>,<NA>
2,SI,2021-04-14,94.0,-1.52,6.19,"Jansen, Kenley",606132,445276,None,foul,<NA>,<NA>,<NA>,<NA>,1,Foul,R,L,R,LAD,COL,S,<NA>,None,0,...,0.077,94.1,2,-2,0.967,0.033,33,27,34,27,1,4,3,1,2,1,1.01,0.48,-0.48,67.7,<NA>,<NA>,<NA>,<NA>,<NA>
3,FC,2021-04-14,93.6,-1.6,6.22,"Jansen, Kenley",606132,445276,None,called_strike,<NA>,<NA>,<NA>,<NA>,5,Called Strike,R,L,R,LAD,COL,S,<NA>,None,0,...,0.049,<NA>,2,-2,0.964,0.036,33,27,34,27,1,4,3,1,2,1,1.12,-0.62,0.62,67.6,<NA>,<NA>,<NA>,<NA>,<NA>
4,FC,2021-04-14,89.8,-1.7,6.19,"Jansen, Kenley",641658,445276,strikeout,swinging_strike,<NA>,<NA>,<NA>,<NA>,3,Garrett Hampson strikes out swinging.,R,R,R,LAD,COL,S,2,None,3,...,0.324,<NA>,2,-2,0.897,0.103,33,26,34,27,1,4,3,1,2,1,1.48,-0.78,-0.78,68.6,<NA>,<NA>,<NA>,<NA>,<NA>

## Save Data

Save the collected data to CSV files for use in feature engineering.

In [ ]:
from pathlib import Path

# Create output directory
output_dir = Path(f"../{DATA_DIR}/raw")
output_dir.mkdir(parents=True, exist_ok=True)

# Save to CSV
# team_batting.to_csv(output_dir / "team_batting.csv", index=False)
pitcher_season.to_csv(output_dir / "pitcher_season.csv", index=False)
pitcher_games.to_csv(output_dir / "pitcher_games.csv", index=False)

# Save pitches to parquet (more efficient for large datasets)
pitches.to_parquet(output_dir / "pitches.parquet", index=False)

print(f"Saved data to {output_dir.resolve()}")
# print(f"  - team_batting.csv: {len(team_batting):,} rows")
print(f"  - pitcher_season.csv: {len(pitcher_season):,} rows")
print(f"  - pitcher_games.csv: {len(pitcher_games):,} rows")
print(f"  - pitches.parquet: {len(pitches):,} rows")

clear_mem()

Saved data to /Users/matthewgillies/PitcherGamePreds/data/raw
  - team_batting.csv: 120 rows
  - pitcher_season.csv: 3,498 rows
  - pitcher_games.csv: 26,067 rows
  - pitches.parquet: 3,860,179 rows